name: UpdateVersion

on:
  push:
    branches: [ master ]

jobs:
  UpdateVersion:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Update Version Number
      run: dotnet fsi ./UpdateVersion.fsx
    - name: Update version.txt
      uses: test-room-7/action-update-file@v1 
      with: 
        file-path: ./version.txt
        commit-msg: Update Version
        github-token: ${{ secrets.KEY_FOR_LAUNCHER }}
